src/user/views.py
from flask.wrappers import Response
from flask.templating import render_template
from flask.globals import request
from flask.helpers import url_for
from werkzeug.utils import redirect
from commons.api import Blueprint
from user import service

user = Blueprint('user', __name__)

@user.route('/register', methods=['GET', 'POST'])
def index() -> Response:
    context = {}
    return Response(render_template('register.html', **context))


@user.route('/login', methods=['GET', 'POST'])
def login() -> Response:
    context = {}

    if request.method == 'POST':
        user_auth = service.login(request.form)
        if user_auth:
            access_token = service.access_token(user_auth)
            return redirect(url_for('home.index'))

    return Response(render_template('login.html', **context))

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ static_url('static/favicon', filename='globe.ico') }}">
    <link rel="stylesheet" type="text/css" href="{{ static_url('static', filename='css/main.css') }}">
    <title>GeoT</title>
</head>
<body>
    <nav class="navbar is-success is-spaced" role="navigation" aria-label="main navigation">
        <div class="container">
            <div class="navbar-menu">
                <div class="navbar-end">
                    <a class="navbar-item" href="{{ url_for('user.index') }}">
                        Sign up
                    </a>
                    <a class="navbar-item" href="{{ url_for('user.login') }}">
                        Sign in
                    </a>
                    <a class="navbar-item" href="#">
                        API-v1.0 Docs
                    </a>
                </div>
            </div>
        </div>
    </nav>

    <section class="section">
        <div class="container">
            {% block content %}{% endblock %}
        </div>
    </section>
    <script src="{{ static_url('static', filename='js/main.js') }}"></script>
</body>
</html>

src/templates/welcome.html
{% extends "base.html" %}

{% block content %}
    <h1>Welcome user</h1>
{% endblock %}